Repository MotiaDev/motia, pull requests merged in 2025-09, with the labels that each got.

#711 chore(docs): missing meta.json fixed
  packages/docs/content/docs/examples/meta.json
Labels: size/XS

#725 refactor: update endpoint plugin structure and enhance UI components
  packages/e2e/src/page-objects/EndpointPage.ts
  packages/e2e/tests/workbench/endpoint-call.spec.ts
  packages/ui/package.json
  packages/ui/src/components/ui/checkbox.stories.tsx
  packages/ui/src/components/ui/checkbox.tsx
  packages/ui/src/components/ui/input.tsx
  packages/ui/src/components/ui/select.tsx
  packages/ui/src/components/ui/tooltip.stories.tsx
  packages/ui/src/components/ui/tooltip.tsx
  packages/ui/src/index.ts
  packages/ui/src/stores/use-theme-store.tsx
  packages/workbench/src/components/header/header.tsx
  packages/workbench/src/components/ui/json-editor.tsx
  packages/workbench/src/components/ui/theme-toggle.tsx
  packages/workbench/src/publicComponents/base-node/code-display.tsx
  plugins/plugin-endpoint/package.json
  plugins/plugin-endpoint/src/components/configuration-list-item.tsx
  plugins/plugin-endpoint/src/components/endpoint-badge.tsx
  plugins/plugin-endpoint/src/components/endpoint-path-preview.tsx
  plugins/plugin-endpoint/src/components/endpoint-path.tsx
  plugins/plugin-endpoint/src/components/json-editor.tsx
  plugins/plugin-endpoint/src/endpoint-badge.tsx
  plugins/plugin-endpoint/src/endpoint-body-panel.tsx
  plugins/plugin-endpoint/src/endpoint-call.tsx
  plugins/plugin-endpoint/src/endpoint-description.tsx
  plugins/plugin-endpoint/src/endpoint-query-params-panel.tsx
  plugins/plugin-endpoint/src/endpoint-response-schema.tsx
  plugins/plugin-endpoint/src/endpoint-response.tsx
  plugins/plugin-endpoint/src/endpoint-side-panel.tsx
  plugins/plugin-endpoint/src/endpoints-page.tsx
  plugins/plugin-endpoint/src/hooks/use-endpoint-configuration.ts
  plugins/plugin-endpoint/src/hooks/use-global-store.ts
  plugins/plugin-endpoint/src/hooks/use-json-schema-to-json.ts
  plugins/plugin-endpoint/src/hooks/use-path-url.ts
  plugins/plugin-endpoint/src/response-body.tsx
  plugins/plugin-endpoint/src/side-panel-body-tab.tsx
  plugins/plugin-endpoint/src/side-panel-headers-tab.tsx
  plugins/plugin-endpoint/src/side-panel-params-tab.tsx
  plugins/plugin-endpoint/src/side-panel-response.tsx
  plugins/plugin-endpoint/src/side-panel.tsx
  plugins/plugin-endpoint/src/stores/use-global-store.ts
  plugins/plugin-endpoint/src/stores/use-theme-store.tsx
  plugins/plugin-endpoint/src/styles.css
  plugins/plugin-endpoint/src/trigger-button.tsx
  pnpm-lock.yaml
Labels: size/XL

#731 feat: enhance endpoint management with search and grouping functionality
  packages/core/src/endpoints/api-endpoints.ts
  packages/e2e/src/page-objects/EndpointPage.ts
  packages/e2e/tests/workbench/endpoint-call.spec.ts
  plugins/plugin-endpoint/src/components/endpoint-item.tsx
  plugins/plugin-endpoint/src/components/endpoints-search.tsx
  plugins/plugin-endpoint/src/components/flow-group.tsx
  plugins/plugin-endpoint/src/endpoints-page.tsx
  plugins/plugin-endpoint/src/hooks/use-get-endpoints.ts
  plugins/plugin-endpoint/src/types/endpoint.ts
Labels: size/M

#741 refactor: improve key handling and structure in EndpointPath and SidePanelBodyTab components
  plugins/plugin-endpoint/src/components/endpoint-path.tsx
  plugins/plugin-endpoint/src/play/side-panel-body-tab.tsx
Labels: size/XS

#749 refactor: update layout styles in Panel, Tabs, and App components for improved responsiveness
  packages/ui/src/components/ui/panel.tsx
  packages/ui/src/components/ui/tabs.tsx
  packages/workbench/src/App.tsx
Labels: size/XS
