Repository MotiaDev/motia, pull requests merged in 2025-10, with the labels that each got.

#763 fix: label renamed from created to registered
  packages/core/src/printer.ts
Labels: size/XS

#762 Enhance README with additional features description
  README.md
Labels: size/XS

#755 chore(docs/dev): ASteps changes and triggers added/ Build your first app - API Endpoints example added, AI Development enabled for more tools
  README.md
  packages/docs/app/docs/[[...slug]]/page.tsx
  packages/docs/content/docs/ai-development-guide.mdx
  packages/docs/content/docs/api-reference.mdx
  packages/docs/content/docs/community-resources.mdx
  packages/docs/content/docs/concepts/deployment/meta.json
  packages/docs/content/docs/concepts/overview.mdx
  packages/docs/content/docs/concepts/steps.mdx
  packages/docs/content/docs/concepts/steps/meta.json
  packages/docs/content/docs/concepts/steps/triggers.mdx
  packages/docs/content/docs/development-guide/meta.json
  packages/docs/content/docs/development-guide/middleware.mdx
  packages/docs/content/docs/development-guide/project-structure.mdx
  packages/docs/content/docs/development-guide/state-management.mdx
  packages/docs/content/docs/getting-started/build-your-first-motia-app/api-endpoints.mdx
  packages/docs/content/docs/getting-started/build-your-first-motia-app/index.mdx
  packages/docs/content/docs/getting-started/build-your-first-motia-app/meta.json
  packages/docs/content/docs/getting-started/meta.json
  packages/docs/content/docs/getting-started/quick-start.mdx
  packages/docs/content/docs/img/build-your-first-app/api-workbench.png
  packages/docs/content/docs/img/build-your-first-app/create-api.png
  packages/docs/content/docs/img/build-your-first-app/delete-pet.png
  packages/docs/content/docs/img/build-your-first-app/get-pet-by-id.png
  packages/docs/content/docs/img/build-your-first-app/interactive-tutorial.png
  packages/docs/content/docs/img/build-your-first-app/list-pets.png
  packages/docs/content/docs/img/build-your-first-app/update-pet.png
  packages/docs/content/docs/index.mdx
  packages/snap/src/cursor-rules/dot-files/.aider.conf.yml
  packages/snap/src/cursor-rules/dot-files/.claude/agents/motia-developer.md
  packages/snap/src/cursor-rules/dot-files/.cursor/rules/motia/api-steps.mdc
  packages/snap/src/cursor-rules/dot-files/.cursor/rules/motia/cron-steps.mdc
  packages/snap/src/cursor-rules/dot-files/.cursor/rules/motia/event-steps.mdc
  packages/snap/src/cursor-rules/dot-files/.cursor/rules/motia/realtime-streaming.mdc
  packages/snap/src/cursor-rules/dot-files/AGENTS.md
  packages/snap/src/cursor-rules/dot-files/CLAUDE.md
  packages/snap/src/cursor-rules/dot-files/opencode.json
Labels: size/L, size/XL

#785 feat: add support to different response types
  packages/core/package.json
  packages/core/src/call-step-file.ts
  packages/core/src/endpoints/api-endpoints.ts
  packages/core/src/types.ts
  playground/steps/test/download-html.step.ts
  playground/steps/test/download-pdf.step.ts
  playground/steps/test/index.html
  playground/steps/test/sample.pdf
  playground/types.d.ts
  plugins/plugin-endpoint/package.json
  plugins/plugin-endpoint/src/hooks/use-endpoint-configuration.ts
  plugins/plugin-endpoint/src/hooks/use-state-stream.ts
  plugins/plugin-endpoint/src/play/response-content.tsx
  plugins/plugin-endpoint/src/play/side-panel-response.tsx
  plugins/plugin-endpoint/src/play/side-panel.tsx
  plugins/plugin-endpoint/src/spec/spec-response-schema.tsx
  pnpm-lock.yaml
Labels: size/M

#779 feat: introduce plugin system for motia workbench
  packages/core/index.ts
  packages/core/src/config.ts
  packages/core/src/server.ts
  packages/core/src/types.ts
  packages/core/src/types/app-config-types.ts
  packages/e2e/src/page-objects/WorkbenchPage.ts
  packages/snap/src/dev.ts
  packages/snap/src/generate-plugins.ts
  packages/snap/src/start.ts
  packages/workbench/middleware.ts
  packages/workbench/package.json
  packages/workbench/src/App.tsx
  packages/workbench/src/components/flow/flow-page.tsx
  packages/workbench/src/components/logs/logs-tab-label.tsx
  packages/workbench/src/components/observability/trace-tab-label.tsx
  packages/workbench/src/components/states/state-tab-label.tsx
  packages/workbench/src/index.css
  packages/workbench/src/lib/plugins.tsx
  packages/workbench/src/lib/utils.ts
  packages/workbench/src/project-view-mode.tsx
  packages/workbench/src/stores/use-app-tabs-store.ts
  packages/workbench/src/stores/use-tabs-store.ts
  packages/workbench/src/system-view-mode.tsx
  packages/workbench/src/vite-env.d.ts
  packages/workbench/tsconfig.node.json
  packages/workbench/vite-plugin-motia-plugins.ts
  playground/motia-workbench.json
  playground/motia.config.ts
  playground/package.json
  playground/types.d.ts
  plugins/plugin-endpoint/src/components/endpoint-tab-label.tsx
  plugins/plugin-endpoint/src/index.ts
  pnpm-lock.yaml
Labels: size/XL

#759 feat: infrastructure config rfc
  contributors/rfc/2025-10-01-infrastructure-config.md
Labels: size/M, size/S

#757 feat: custom runtimes and plugin rfc
  contributors/rfc/2025-10-01-custom-runtimes-global-config-plugins.md
Labels: size/M
